    export {default as HomeHero} from './HomeHero/home-hero'
    export {default as ChooseCar} from './choose-your-car/choose-your-car'
    export {default as OurAdvenSlider} from './our-advantage/our-advantage'
    export { default as SpecialOfferComp} from './special-offer-component/special-offer-component'
    export {default as AboutUsSlider } from './about-us-component/about-us-component'
    export {default as NewsSlider} from './news-slider/news-slider'